/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.locustsRUs.locusts

import kotlin.test.Test
import kotlin.test.assertEquals

class LibraryTest {
  @Test
  fun locustsShouldGetIntroduced() {
    assertEquals(Locusts.introduceLocusts(), Unit, "Locusts should be introduced")
  }
}
