/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("maven-publish")
    id("net.researchgate.release") version "3.0.2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.0.0")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            groupId = "io.github.locusts-r-us"
            artifactId = "locusts"
            version = "0.1.0"
            pom {
                name = "Locusts"
                description = "A JVM library that introduces locusts into your codebase."
                licenses {
                    license {
                        name = "Zero-Clause BSD"
                        url = "https://spdx.org/licenses/0BSD.html"
                    }
                }
                developers {
                    developer {
                        id = "rosstheross"
                        name = "Matt Strapp"
                        email = "matt@mattstrapp.net"
                    }
                }
                scm {
                    connection = "scm:git:https://github.com/locusts-r-us/locusts.git"
                    developerConnection = "scm:git:ssh://github.com/locusts-r-us/locusts.git"
                    url = "https://github.com/locusts-r-us/locusts"
                }
            }
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/locusts-r-us/locusts")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

release {
    git {
        requireBranch = "master"
    }
}