name: Deno

on:
  push:
    paths:
      - "src/packages/locusts/mod.ts"
      - "**/deno.json"
      - ".github/workflows/deno.yml"
  pull_request:
    paths:
      - "src/packages/locusts/mod.ts"
      - "**/deno.json"
      - ".github/workflows/deno.yml"

jobs:
  lint-test-and-publish:
    name: Lint and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Lint
        run: |
         deno lint
        #  Weirdly broken
        #  deno fmt --check
      - name: Test
        run: deno test src/packages/locusts/mod.ts
      - name: Publish on Tag
        run: deno run -A jsr:@david/publish-on-tag --allow-dirty