name: Go

on:
  push:
    paths:
      - "**.go"
      - "**go.mod"
      - ".github/workflows/go.yml"
  pull_request:
    paths:
      - "**.go"
      - "**go.mod"
      - ".github/workflows/go.yml"

jobs:
  lint-build-and-test:
    name: Lint, Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v .
